/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctpv;

import javax.swing.JFrame;

/**
 *
 * @author David
 */
public class CTPV_Frame extends javax.swing.JFrame {

    private Terminal_Frame terminal1;
    private Terminal_Frame terminal2;
    private Terminal_Frame terminal3;
    private Terminal_Frame terminal4;
    private Terminal_Frame terminal5;
    private Terminal_Frame terminal6;

    private Terminal_Frame[] lista;

    private Thread servidor;

    /**
     * Creates new form CTPV_Frame
     */
    public CTPV_Frame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.terminal1 = new Terminal_Frame();
        this.terminal1.setTitle("TERMINAL Nº1");
        this.terminal2 = new Terminal_Frame();
        this.terminal2.setTitle("TERMINAL Nº2");
        this.terminal3 = new Terminal_Frame();
        this.terminal3.setTitle("TERMINAL Nº3");
        this.terminal4 = new Terminal_Frame();
        this.terminal4.setTitle("TERMINAL Nº4");
        this.terminal5 = new Terminal_Frame();
        this.terminal5.setTitle("TERMINAL Nº5");
        this.terminal6 = new Terminal_Frame();
        this.terminal6.setTitle("TERMINAL Nº6");
        
        this.getContentPane().add(terminal1, 0);
        this.getContentPane().add(terminal2, 1);
        this.getContentPane().add(terminal3, 2);
        this.getContentPane().add(terminal4, 3);
        this.getContentPane().add(terminal5, 4);
        this.getContentPane().add(terminal6, 5);

        this.lista = new Terminal_Frame[6];
        this.lista[0] = this.terminal1;
        this.lista[1] = this.terminal2;
        this.lista[2] = this.terminal3;
        this.lista[3] = this.terminal4;
        this.lista[4] = this.terminal5;
        this.lista[5] = this.terminal6;

        this.servidor = new Thread(new Server(this));
        this.servidor.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CTPV");
        getContentPane().setLayout(new java.awt.GridLayout(2, 3));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTPV_Frame().setVisible(true);
            }
        });
    }

    public int primeroLibre() {
        int x = -1;
        for (int i = 0; i < 6; i++) {
            Terminal_Frame aux = lista[i];
            if (aux.isVisible() == false) {
                x = i;
                break;
            }
        }
        return x;

    }

    public Terminal_Frame devuelveTerminal() {
        Terminal_Frame aux = null;
        int posicion = primeroLibre();
        if (posicion != -1) {
            aux = lista[posicion];
        }
        aux.reset();
        return aux;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
