/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package central;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author David
 */
public class CTPV_Frame extends javax.swing.JFrame {

//    private Terminal_Frame terminal1;
//    private Terminal_Frame terminal2;
//    private Terminal_Frame terminal3;
//    private Terminal_Frame terminal4;
//    private Terminal_Frame terminal5;
//    private Terminal_Frame terminal6;
    private Terminal_Frame[] lista;

    private Thread servidor;

    private Facturacion facturacion;
    private File fichero;

    /**
     * Creates new form CTPV_Frame
     */
    public CTPV_Frame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

//        this.terminal1 = new Terminal_Frame();
//        this.terminal1.setTitle("TERMINAL Nº1");
//        this.terminal2 = new Terminal_Frame();
//        this.terminal2.setTitle("TERMINAL Nº2");
//        this.terminal3 = new Terminal_Frame();
//        this.terminal3.setTitle("TERMINAL Nº3");
//        this.terminal4 = new Terminal_Frame();
//        this.terminal4.setTitle("TERMINAL Nº4");
//        this.terminal5 = new Terminal_Frame();
//        this.terminal5.setTitle("TERMINAL Nº5");
//        this.terminal6 = new Terminal_Frame();
//        this.terminal6.setTitle("TERMINAL Nº6");
//        
//        this.getContentPane().add(terminal1, 0);
//        this.getContentPane().add(terminal2, 1);
//        this.getContentPane().add(terminal3, 2);
//        this.getContentPane().add(terminal4, 3);
//        this.getContentPane().add(terminal5, 4);
//        this.getContentPane().add(terminal6, 5);
        this.lista = new Terminal_Frame[6];
//        this.lista[0] = this.terminal1;
//        this.lista[1] = this.terminal2;
//        this.lista[2] = this.terminal3;
//        this.lista[3] = this.terminal4;
//        this.lista[4] = this.terminal5;
//        this.lista[5] = this.terminal6;

        this.servidor = new Thread(new Server(this));
        this.servidor.start();

        this.fichero = new File("Ventas.dat");
        try {

            System.out.println(fichero.createNewFile());
            this.facturacion = new Facturacion(fichero);
        } catch (IOException ex) {
            Logger.getLogger(CTPV_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CTPV");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Icono/Tienda.jpg")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                prueba(evt);
            }
        });

        jDesktopPanel.setLayout(new java.awt.GridLayout(2, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prueba(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_prueba
        // TODO add your handling code here:
    }//GEN-LAST:event_prueba

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTPV_Frame().setVisible(true);
            }
        });
    }

    public int primeroLibre() {
        int x = -1;
        for (int i = 0; i < 6; i++) {

            if (lista[i] == null) {
                x = i;
                break;
            }
        }
        return x;

    }

    /**
     * Método que inserta el terminal que recibe como parametro en el panel
     * contenedor del frame
     *
     * @param terminal
     */
    public void insertarTerminal(Terminal_Frame terminal) {
        int i = primeroLibre();

        this.jDesktopPanel.add(terminal);

        terminal.setVisible(true);

        this.lista[i] = terminal;
    }

    /**
     * Método que borra del panel contenedor del frame el Terminal_frame que
     * recibe como parametro y devuelve true si lleva a cabo la operación y
     * false si no se lleva a cabo.
     *
     * @param terminal
     * @return boolean
     */
    public boolean borrarTerminal(Terminal_Frame terminal) {
        boolean hecho = false;

        for (int i = 0; i < 6; i++) {

            if (this.lista[i] == terminal) {
                this.lista[i] = null;
                this.jDesktopPanel.setVisible(false);
                this.jDesktopPanel.remove(terminal);
                this.jDesktopPanel.setVisible(true);
                this.repaint();
                hecho = true;
                break;
            }
        }

        return hecho;

    }

//    private void repintar(){
//        this.removeAll();
//        for (int i = 0; i < 6; i++) {
//            this.add(this.lista[i]);
//        }
//        this.repaint();
//    }
//    public Terminal_Frame devuelveTerminal() {
//        Terminal_Frame aux = null;
//        int posicion = primeroLibre();
//        if (posicion != -1) {
//            aux = lista[posicion];
//        }
//        aux.reset();
//        return aux;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanel;
    // End of variables declaration//GEN-END:variables
    
    //**************************************************************************
    //GETTERS & SETTERS
    
    public Terminal_Frame[] getLista() {
        return lista;
    }

    public void setLista(Terminal_Frame[] lista) {
        this.lista = lista;
    }

    public Thread getServidor() {
        return servidor;
    }

    public void setServidor(Thread servidor) {
        this.servidor = servidor;
    }

    public javax.swing.JDesktopPane getjDesktopPanel() {
        return jDesktopPanel;
    }

    public void setjDesktopPanel(javax.swing.JDesktopPane jDesktopPanel) {
        this.jDesktopPanel = jDesktopPanel;
    }

    public Facturacion getFacturacion() {
        return facturacion;
    }

}
