/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package central;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author David
 */
public class CTPV_Frame extends javax.swing.JFrame {

    private Terminal_Frame[] lista;

    private Thread servidor;

//    private Facturacion facturacion;
    private File fichero;
//    private FileWriter out;
    private PrintWriter out;

    /**
     * Creates new form CTPV_Frame
     */
    public CTPV_Frame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.lista = new Terminal_Frame[6];

        this.servidor = new Thread(new Server(this));
        this.servidor.start();

        this.fichero = new File("Ventas.dat");

        try {

            System.out.println(fichero.createNewFile());
            this.out = new PrintWriter (new FileWriter(fichero,true));
//            this.facturacion = new Facturacion(fichero);
        } catch (IOException ex) {
            Logger.getLogger(CTPV_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CTPV");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Icono/Tienda.jpg")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrarTodo(evt);
            }
        });

        jDesktopPanel.setLayout(new java.awt.GridLayout(2, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarTodo(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrarTodo
        out.close();
    }//GEN-LAST:event_cerrarTodo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTPV_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTPV_Frame().setVisible(true);
            }
        });
    }

    /**
     * Método que devuelve la primera posición disponible de la lista de
     * terminales
     *
     * @return
     */
    public int primeroLibre() {
        int x = -1;
        for (int i = 0; i < 6; i++) {

            if (lista[i] == null) {
                x = i;
                break;
            }
        }
        return x;

    }

    /**
     * Método que inserta el terminal que recibe como parametro en el panel
     * contenedor del frame
     *
     * @param terminal
     */
    public void insertarTerminal(Terminal_Frame terminal) {
        int i = primeroLibre();

        this.jDesktopPanel.add(terminal);

        terminal.setVisible(true);

        this.lista[i] = terminal;
    }

    /**
     * Método que borra del panel contenedor del frame el Terminal_frame que
     * recibe como parametro y devuelve true si lleva a cabo la operación y
     * false si no se lleva a cabo.
     *
     * @param terminal
     * @return boolean
     */
    public boolean borrarTerminal(Terminal_Frame terminal) {
        boolean hecho = false;

        for (int i = 0; i < 6; i++) {

            if (this.lista[i] == terminal) {
                this.lista[i] = null;
                this.jDesktopPanel.setVisible(false);
                this.jDesktopPanel.remove(terminal);
                this.jDesktopPanel.setVisible(true);
                this.repaint();
                hecho = true;
                break;
            }
        }

        return hecho;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanel;
    // End of variables declaration//GEN-END:variables

    //**************************************************************************
    //GETTERS & SETTERS
    public Terminal_Frame[] getLista() {
        return lista;
    }

    public void setLista(Terminal_Frame[] lista) {
        this.lista = lista;
    }

    public Thread getServidor() {
        return servidor;
    }

    public void setServidor(Thread servidor) {
        this.servidor = servidor;
    }

    public javax.swing.JDesktopPane getjDesktopPanel() {
        return jDesktopPanel;
    }

    public void setjDesktopPanel(javax.swing.JDesktopPane jDesktopPanel) {
        this.jDesktopPanel = jDesktopPanel;
    }

    public File getFichero() {
        return fichero;
    }

    public PrintWriter getOut() {
        return out;
    }
//    public Facturacion getFacturacion() {
//        return facturacion;
//    }

}
