/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package central;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class Terminal_Frame extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla; //Modelo de la tabla que contiene la factura

    /**
     * Creates new form venta
     */
    public Terminal_Frame() {
        initComponents();
        this.modeloTabla = new DefaultTableModel();

        //Añadimos las columnas a la tabla
        this.modeloTabla.addColumn("Productos");
        this.modeloTabla.addColumn("Cantidad");
        this.modeloTabla.addColumn("Sub-total");

        this.jTableLineasCompra.setModel(modeloTabla);// Añadimos el modelo a la tabla
        
    }

    /**
     * Método que se encarga de vaciar los datos de DefaultTableModel 
     * Retorna true si consigue llevar a cabo la operación y false si no se consigue
     * 
     * @return boolean
     */
    public boolean vaciar() {
        if (this.modeloTabla.getRowCount() > 0) {
            int a = modeloTabla.getRowCount() - 1;
            for (int i = a; i >= 0; i--) {
                modeloTabla.removeRow(i);
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * Método que devuelve el Terminal_Frame a su estado inicial
     */
    public void reset() {

        vaciar();
        this.jLabelTotal.setText("€");
        this.setVisible(false);
    }

    /**
     * Método que se encarga de guardar en el archivo que recibe como parametro 
     * los datos de la compra y 
     * de informar a través de una ventana emergente que la 
     * compra ha sido finalizada y que el Terminal_Frame se va a cerrar.
     */
    public void compraFinalizada(){      
        
        JOptionPane.showMessageDialog(this, "Compra finalizada");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLineasCompra = new javax.swing.JTable();

        setIconifiable(true);

        jLabel1.setText("Ticket de compra");

        jLabel2.setText("Total ticket");

        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("€");

        jTableLineasCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableLineasCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114))
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableLineasCompra;
    // End of variables declaration//GEN-END:variables

//*******************************************************************************
//GETTERS & SETTERS

    public javax.swing.JLabel getjLabelTotal() {
        return jLabelTotal;
    }

    public void setjLabelTotal(javax.swing.JLabel jLabelTotal) {
        this.jLabelTotal = jLabelTotal;
    }

    public javax.swing.JTable getjTableLineasCompra() {
        return jTableLineasCompra;
    }

    public void setjTableLineasCompra(javax.swing.JTable jTableLineasCompra) {
        this.jTableLineasCompra = jTableLineasCompra;
    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void setModeloTabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }

}
